### ISSUE TITLE
ENH: Only pull 2019 events

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#102]
## Expected Behavior
We decided to only list events for 2019, so can you adjust the scrapers to only pull those? We kept the 2020 ones in a separate sheet for fear we may not capture them on the next scrape.

## Current Behavior
Scraper currently pulling 2020 events.

## Possible Solution
Code to ignore 7 months in future

## Context
It will take us less time to curate the .csv if the 2020 events are not included.

**Comment by csmcallister** [comment]
closed by 5d2ef50
