### ISSUE TITLE
ENH: Was there ever a scraper for Anacostia Watershed Society (AWS)?

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#103]
## Expected Behavior
We thought AWS was being scraped. Was there an issue requiring it to be manually scraped?

Event calendar here:  https://www.anacostiaws.org/events-calendar.html

## Current Behavior
AWS not being scraped

## Possible Solution
Create scraper for AWS if possible.

## Context
AWS is an important ally to Capital Nature so we'd like to capture their events. We just need to know if they should be manual scrapes.

**Comment by csmcallister** [comment]
Somebody name An (I *think* Nguyen) was working on this but I haven't seen/heard from them. I'll reach out to them on Slack to see.

**Comment by csmcallister** [comment]
An fell off so I'll make a new issue requesting this source to be scraped as a priority @akaahanui
