### ISSUE TITLE
ENH: Please create a scrape log

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#107]
## Expected Behavior
We'd like to be able to see dates when the scrapers are run and if there are any event sources that are broken. 

## Current Behavior
We don't have a central place to find scraper status at a glance.

## Context
This log inform whether or not we need to do manual scrapes on certain event sources.

**Comment by csmcallister** [comment]
I currently log errors that break a certain event source when running the scraper for all events, so we're most of the way toward solving this. @akaahanui let me do some thinking on the format of this log and then let's see what'll work best for you et al. I'm assuming an excel file of some sort would be best, so correct me if I'm wrong.

**Comment by akaahanui** [comment]
HI @csmcallister! I wanted to circle back on the scrape log. Excel or Google sheet would be fine. Now that we have 3 volunteers looking for events, we're trying to keep track of which manual ones we should be focusing on. I see we have a ticket for NOVA Parks, which is good, as one of our volunteers did a manual scrape last week. If that scrape goes live, let me know so we can take that off our manual list.

Thanks!

**Comment by csmcallister** [comment]
I haven't had a chance yet to work on these logs. I was hoping we could discuss what this log file should look like at this week's DataJam. Since neither you nor Stella can make it, could you attach an excel file to this issue that contains the columns you'd expect to see in this log file?

**Comment by akaahanui** [comment]
@csmcallister The log can be really simple. Here is a mock-up for consideration and comment.

https://docs.google.com/spreadsheets/d/1B1nQCWgiSL4wjOPnaJsiangt9_2Hk6M9AZUW_6mcjKY/edit?usp=sharing

Here is a link to the calendar process flow doc we reviewed on our last call. Just wanted to share as reminder to see if you had any comments or edits we should make:

https://docs.google.com/spreadsheets/d/1B1nQCWgiSL4wjOPnaJsiangt9_2Hk6M9AZUW_6mcjKY/edit?usp=sharing

Thanks so much for the scrape this week and all the amazing work you are doing!

**Comment by rachelauryn** [comment]
Notes from discussion about design of log:
- Google sheet that auto-updates whenever scrape is run
- Scrape should run every month, the log should maintain data from the last 3 months (one tab per scrape/month would be ideal)
- Tab 1 columns: number of event sources scraped successfully & number of events scraped
- Tab 2 is error log: columns: 1 date of scrape, 2 name of source, 3 name of event, & 4 error message (purpose: for CN to know where to go for manual scraping if needed & to give to de-bugger)

**Comment by csmcallister** [comment]
Closed by c69d6d7

**Comment by csmcallister** [comment]
@akaahanui I just added support having the logs as well as a scrape report in two separate spreadsheets. Please see the attached spreadsheet, which is an example of the scrape report, and let me know what you think. The log spreadsheet is more useful for us developers since it contains the info we'd need to debug.

[scrape-report-11-17-2019.xls.zip](https://github.com/DataKind-DC/capital-nature-ingest/files/3855967/scrape-report-11-17-2019.xls.zip)

There's a row for each event source (column A) and the additional columns let you know how many events were scraped for that source, what sorts of errors there were, and, most importantly, that event source's "status".

**Comment by akaahanui** [comment]
@csmcallister HI Scott - you can ignore the silly question in my email to you about an "inbox" in GitHub. I have no idea why I didn't check the chat for the issue. D'uh Ana!

**Comment by csmcallister** [comment]
Closing this unless there's an issue with the report (see the example above).
