### ISSUE TITLE
ENH: New event source - Nova Parks

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#108]
## Event Source Calendar
https://www.novaparks.com/things-to-do

## Context
This is a nice-to-have identified in June's DataJam.

## Are we scraping it?
 - [ ] Yes, we are!

**Comment by azpoliak** [comment]
Looking into it

**Comment by csmcallister** [comment]
Hey @azpoliak! Sorry I didn't see your comment earlier. I've just assigned this to you so that others are aware. Feel free to reach out here or in Slack if you've got any questions or need help.

**Comment by csmcallister** [comment]
Hey @azpoliak. Any progress on this? Otherwise I'll unassign you so others can work on it.

**Comment by NicoleJaneway** [comment]
It looks like NOVA Parks is using eventbrite

**Comment by csmcallister** [comment]
Do you want to take this one @NicoleJaneway ?

**Comment by NicoleJaneway** [comment]
Sure 👍

**Comment by csmcallister** [comment]
Closed by d4f6acd
