### ISSUE TITLE
ENH: New event source: Eleventh Street Bridge 

### ISSUE THREAD

**Issue by preischer** [DataKind-DC/capital-nature-ingest#109]
## Expected Behavior

Event Source for the [Eleventh Street Bridge Park](https://bbardc.org/events/)
## Current Behavior

We don't have one!

**Comment by csmcallister** [comment]
Melissa was previously working on this but dropped off, so it's now open for anyone else.

**Comment by preischer** [comment]
I'm working on this, not sure how to assign myself? BBAR is also a duplicate of this issue.

**Comment by csmcallister** [comment]
Sounds good @preischer. I [assigned](https://help.github.com/en/articles/assigning-issues-and-pull-requests-to-other-github-users) you to this issue so that others can see you're on it. Thanks and feel free to holler if you've got any questions.

**Comment by csmcallister** [comment]
closed by 596cc99
