### ISSUE TITLE
ENH: New Event Source:  U.S. Botanic Gardens

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#113]
## Event Source Calendar

https://learn.usbg.gov/calendar/event

## Can we scrape it?
It appears to be scrape-able with BeautifulSoup

## Context
This is a nice-to-have.

## Are we scraping it?
- [x] yes we are!

**Comment by jmelot** [comment]
Just stumbled on DataKind DC! I have some time this weekend - can work on this.

**Comment by csmcallister** [comment]
Big thanks @jmelot!
