### ISSUE TITLE
ENH: New event source:  U.S. National Arboretum

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#114]
## Event Source Calendar
https://usna.usda.gov/visit/events-calendar/

## Context
This is a nice-to-have.

## Are we scraping it?
- [ ] yes, we are!

**Comment by hunjwaslike** [comment]
I can try scraping this. I dont think it will be difficult.

**Comment by csmcallister** [comment]
Awesome @hunjwaslike 

Please note that I added some instructions on how to include a test for your scraper in the CONTRIBUTING.MD file. Basically, all you need to do is copy-paste one of the other tests that have been written and then change one line of code to reflect the name of the file you wrote your scraper in. Feel free to reach out on Slack if you've got questions.

**Comment by csmcallister** [comment]
Dupe of #174, so I'm closing this as stale.
