### ISSUE TITLE
ENH: New Event Source: Little Falls Watershed Alliance

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#120]
## Event Source Calendar

https://www.lfwa.org/events

## Context
This is a nice-to-have.

## Are we scraping it?
 - [x] Yes, we are!

**Comment by vabigdatamover** [comment]
@csmcallister , add me to the Little Falls Watershed Alliance

**Comment by csmcallister** [comment]
This looks like one where you'll need to scrape each event's individual page. The [required data](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/event_schema.md) seems present and consistently presented though. Each event page actually has a link to a calendar file, which should be easy to extract everything you'd need using either [ics](https://pypi.org/project/ics/) or [icalendar](https://pypi.org/project/icalendar/) @vabigdatamover

**Comment by csmcallister** [comment]
Closed by f056159 thanks to @Frankie-Figz
