### ISSUE TITLE
ENH: New event source: Earth Conservation Corps

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#123]
## Event Source Calendar
https://www.earthconservationcorps.org/events-1

## Context
This is a nice-to-have.

## Are we scraping it?
 - [ ] Yes, we are!

**Comment by wkarney** [comment]
FYI: Currently looks like their website is down / under construction: <img width="717" alt="Screen Shot 2019-09-18 at 1 50 53 PM" src="https://user-images.githubusercontent.com/35663282/65337377-01020e00-db96-11e9-8fdc-a004d0368314.png">

**Comment by csmcallister** [comment]
@akaahanui Do you have any insight into this?

**Comment by akaahanui** [comment]
@csmcallister I do not but I will see what I can find out. Should I just be asking when then new site will be live?

**Comment by csmcallister** [comment]
@akaahanui in order to get events from this source, we'll eventually need to know what the new url is. If you don't mind, could you please comment in this issue once the new site is up? Then we can re-evaluate whether or not the event source is scrapable.

**Comment by akaahanui** [comment]
@csmcallister  Will do!

**Comment by MDshuey** [comment]
If the new website is up and running here's how to get the agenda *from* the current day.
Today for example:

https://earthconservationcorps.org/events/list/?tribe-bar-date=2020-01-21

Unfortunately no events have been listed yet for the year, but we can practice scraping by using an old date in the HTML.

**Comment by csmcallister** [comment]
Thanks for looking into this one @MDshuey and it was nice meeting you last night. Would you want me to assign this one to you so you can work on it??

**Comment by MDshuey** [comment]
@csmcallister Sure thing Scott

**Comment by csmcallister** [comment]
@akaahanui and @MDshuey Just noticed that this event source never has events on its events page. So I'm going to close this until there are events. We can re-open if/when that happens.
