### ISSUE TITLE
ENH: New event source: DC Audubon Society

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#126]
## Event Source Calendar
https://www.eventbrite.com/o/dc-audubon-10726377705

## Can we scrape it?
We can use the Eventbrite API.

## Context
This is a nice-to-have.

## Are we scraping it?
- [x] Yes, we are!

**Comment by csmcallister** [comment]
@stefangouyet I tagged you on this since you had claimed it awhile back. Did you have anything working for this, or should I unassign you so that others can tackle it?

**Comment by wkarney** [comment]
@csmcallister I can take this one on!

**Comment by csmcallister** [comment]
Scraper added with c7dd78f!
