### ISSUE TITLE
BUG: Special characters omitted from Event Description (Montgomery Parks)

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#148]
## Current Behavior
In the latest scrape (7/29/19) there are some events from Montgomery Parks in Spanish. In the Event Descriptions, all the special characters (á, é, í, ó, ú, ü, ñ, ¿, ¡) are removed. Can this be prevented? It might be a problem when scraping other sources, but this is the first time I've noticed it.

Here's an example of such an event: https://www.montgomeryparks.org/events/youth-on-earth-25/

In the scraped CSV file, the event description says:

> (MD) Do you need SSL hours? Do you enjoy being active outdoors? Come join other teens in our Youth on Earth program! Go hiking with new friends, learn about local wildlife, and get up-close encounters with Meadowsides resident animals, including amphibians, reptiles, and raptors. Bring your energy and creativity to environmental projects that impact your community. Bilingual (English/Spanish) program coordinator.Necesitas horas comunitarias? Te gusta hacer actividades al aire libre? nete con otros jvenes en nuestro programa Youth on Earth! Vas a caminar con nuevos amigos, aprender sobre especies locales y encontrar de cerca los animales residentes de Meadowside, por ejemplo anfibios, reptiles y aves rapaces. Trae tu energa y creatividad a proyectos medioambientales que afectan a tu comunidad. Coordinadora bilinge (espaol/ingls).

**Comment by csmcallister** [comment]
Woah! I didn't think this was a possibility when I fixed those weird characters we were getting (#55). Looks like I'll need a more surgical fix.

**Comment by csmcallister** [comment]
fixed by e9f5512 @bmvoss
