### ISSUE TITLE
ENH: New event source: Audubon Society of Northern Virginia

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#168]
## Event Source Calendar
http://audubonva.org/birdwalks-and-field-trips

## Context
This is a priority org. Please pull through the end of Feb 2020.

## Are we scraping it?

**Comment by jmelot** [comment]
I can do this one this weekend if you want!

**Comment by jmelot** [comment]
Finally submitted a PR (sorry, later than I'd hoped!). Let me know if there are any issues, and happy holidays!

**Comment by csmcallister** [comment]
Closed by ad93425
