### ISSUE TITLE
ENH: New event source: Potomac Conservancy

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#171]
## Event Source Calendar

https://potomac.org/events

## Can we scrape it?

It looks doable 👍 

## Context

This is a priority org. They use Eventbrite.
Please pull through the end of Feb 2020.

## Are we scraping it?

**Comment by csmcallister** [comment]
Their [Eventbrite page ](https://www.eventbrite.com/o/potomac-conservancy-8275588434?aff=ebriterally_article_dc)only shows one event for January 18th while https://potomac.org/events shows multiple events. Given the fact that the Eventbrite API is still not functioning properly and the company has yet to make an announcement about their long-term plans for it, I'm going to prioritize web-scraping https://potomac.org/events @akaahanui

**Comment by csmcallister** [comment]
Closed by b50e075 

We're now scraping this @akaahanui !
