### ISSUE TITLE
ENH: Update event source calendar url (Rock Creek Park Conservancy)

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#172]
## Event source calendar

Please update to: https://www.rockcreekconservancy.org/what-we-do/upcoming-events

Please pull through the end of Feb 2020.

**Comment by csmcallister** [comment]
@akaahanui We currently use [this url](https://events.time.ly/8ib56fp), which shows the same events as the one you listed if I'm not mistaken. Is there any reason in particular why the urls should be swapped out? Are we not capturing RCC events in the csv files?

**Comment by akaahanui** [comment]
@csmcallister When we were on the call last week, we asked why RCC was not being scraped and you mentioned that the url in the scrape was different from the one on our spreadsheet. That's why I added the issue, thinking maybe the wrong url was preventing the scrape. I checked the Nov 4 events scraped and RCC was not included. A bug maybe?

**Comment by csmcallister** [comment]
I'll look into this then.

**Comment by csmcallister** [comment]
In the December scrape, the report showed that we scraped 29 events for this source and that there was one additional event that we didn't capture because we couldn't determine a start time for it. That error was fixed in 3c2e09d06758d98a7a8e4e634364cc7c2176080b so I'm going to close this for now.
