### ISSUE TITLE
ENH: New event source: Sierra Club (MD Chapter)

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#173]
## Event Source Calendar
https://www.sierraclub.org/maryland/outings-calendar-maryland

## Context

Please add, since we collect DC and VA Chapter events. Please pull through the end of Feb 2020.

## Are we scraping it?

**Comment by NicoleJaneway** [comment]
It looks like Sierra Club Maryland's chapter uses eventbrite

**Comment by csmcallister** [comment]
Do you also want this one @NicoleJaneway ?

**Comment by NicoleJaneway** [comment]
Got this one too

**Comment by csmcallister** [comment]
Closed by d4f6acd
