### ISSUE TITLE
ENH: New event source: U.S. National Arboretum

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#174]
## Event Source Calendar
https://www.usna.usda.gov/visit/calendar-of-events/

## Context

This is a priority org.  Please pull through the end of Feb 2020.

## Are we scraping it?

**Comment by Gflemin** [comment]
I can grab this one.

**Comment by csmcallister** [comment]
Hi @Gflemin . Any updates on this one? If not, may I unassign you in order to free it up for another contributor?

**Comment by Gflemin** [comment]
Hi Scott,

Yes, unassigning me is fine! I'm sorry I didn't update you on that.

Best,
Grant

**Comment by Frankie-Figz** [comment]
@minh5 Maybe take a look at this as well if the potomac calendar scrape proves too tedious?

**Comment by Frankie-Figz** [comment]
@csmcallister I do not think that this could be scraped so easily given the non-uniform nature of how the are uploading cards to https://www.usna.usda.gov/visit/calendar-of-events.

@minh5 is going to take a more detailed look at it and share his valuation

**Comment by csmcallister** [comment]
> @csmcallister I do not think that this could be scraped so easily given the non-uniform nature of how the are uploading cards to https://www.usna.usda.gov/visit/calendar-of-events.

Yeah, it looks like you'd have to visit each event page to get what you need and then hope that they are consistent. We've done it for other sources in the past, so one would just need to be mindful of where their scraping could break and to catch and log those errors.

**Comment by madhuqmar** [comment]
Hi @minh5 and @csmcallister, I am able to scrape the events from this website- if no one is working on this currently, can you assign me this one so I can make it production-ready? Thanks!

**Comment by csmcallister** [comment]
Thanks @madhuqmar! Feel free to open a PR and reference this issue. I should have a chance to review this evening.

**Comment by madhuqmar** [comment]
Thanks for assigning @csmcallister! I'm testing the scraper now, when it passes all tests will open the PR.

**Comment by Frankie-Figz** [comment]
@csmcallister Hi Scott, I think the correct url for this event source is: 

- https://www.usna.usda.gov/visit/calendar-of-events/

Compate the above with the below. At the beginning of this issue it is labelled as: https://www.usna.usda.gov/visit/events-calendar/

**Comment by csmcallister** [comment]
> @csmcallister Hi Scott, I think the correct url for this event source is:
> 
> * https://www.usna.usda.gov/visit/calendar-of-events/
> 
> Compate the above with the below. At the beginning of this issue it is labelled as: https://www.usna.usda.gov/visit/events-calendar/

I think you're right. I'll update the link up top.

**Comment by csmcallister** [comment]
Issue cleaning...closing for now.
