### ISSUE TITLE
BUG: Audubon Naturalist Society was not on Nov 4 scrape, please troubleshoot

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#176]
## Expected Behavior
Event ans.py should be scraped.

## Current Behavior
This organizer was listed as being scraped on Nov 4th, but there were no events collected.
https://anshome.org/events-calendar/

## Possible Solution
Please troubleshoot or let us know if we should manually pull these events. Thanks!

**Comment by csmcallister** [comment]
I'm working on #107 and this should shed some light. I'll circle back.

**Comment by csmcallister** [comment]
After adding the logging feature and running `get_events.py`, I can confirm that we scraped the 8 November events from the [calendar page](https://anshome.org/events-calendar/). Some extra work needs to be done to make sure we also get events for the 3 next months (i.e. December, January and February).

**Comment by csmcallister** [comment]
closed by ad56e2a which gets events for the current month as well as the next three months for ANS 🎉 @akaahanui This results in 15 events being found, which you can see corresponds to the number of events for Nov-Feb on their [calendar](https://anshome.org/events-calendar/).

**Comment by akaahanui** [comment]
Fantastic work - you rock! Have a wonderful Thanksgiving!
