### ISSUE TITLE
ENH: Event dug_network.py no longer needs to be scraped

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#177]
## Expected Behavior
Since the DUG Network is an event consolidator like we are, we will stop scraping that event to prevent duplicates.

## Current Behavior
DUG is listed as an event, but we have not been seeing them on scrapes.

## Possible Solution
Please remove from scraped events list. Thanks!

**Comment by csmcallister** [comment]
done!

**Comment by akaahanui** [comment]
@csmcallister  Thanks so much!
