### ISSUE TITLE
FIX: Small adjustment to "Contributing" doc

### ISSUE THREAD

**Issue by NicoleJaneway** [DataKind-DC/capital-nature-ingest#180]
## Possible Solution
Last line of code in # 4 of **Testing your Code** should read 
```python3 -W ignore -m unittest tests/<name_of_your_scraper>_test.py``` 
(adds reference to tests directory)

**Comment by csmcallister** [comment]
That's correct @NicoleJaneway! Do you want to add this change to #178 ?

**Comment by NicoleJaneway** [comment]
Done!
