### ISSUE TITLE
ENH: January Scrape

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#194]
@csmcallister 

Happy New Year! Any chance you can do a scrape today for February through April? Thanks for resolving those recent tickets!

Aloha,
Ana

**Comment by csmcallister** [comment]
Happy new year!! 🎉 

I can run it this evening. In the meantime, could you please respond to some of the issues I recently tagged you in?

**Comment by csmcallister** [comment]
done!
