### ISSUE TITLE
ENH: New Event Source: Smithsonian National Museum of Natural History

### ISSUE THREAD

**Issue by madhuqmar** [DataKind-DC/capital-nature-ingest#215]
## Event Source Calendar
https://naturalhistory.si.edu/events 

## Context
This seems relatively simple to scrape. However, I'd like to know if this will really add value to the project.

**Comment by csmcallister** [comment]
Hi @madhuqmar! Thanks for looking into that source! Unfortunately, I don’t think those events really qualify as “outdoorsy”. I will, however, defer to @akaahanui for a final say.

In the meantime, feel free to reach out to anyone assigned to one of the other new event source issues to check if that person is still working on it!

**Comment by akaahanui** [comment]
HI @madhuqmar! Thanks for suggesting. Just to clarify, we do promote indoor educational and cultural events as long as they have to do with nature, so book lectures, citizen science activities would be fair game. I did look at their upcoming events and I don't see enough things that would warrant a scrape. Our manual team can continue on those.

We appreciate your support!
Ana
