### ISSUE TITLE
ENH: New Event Source: Capital Hiking Club

### ISSUE THREAD

**Issue by vabigdatamover** [DataKind-DC/capital-nature-ingest#228]
Check to see if Capital Hiking Club schedule is able to be scraped?

Event Source Calendar

 **https://www.capitalhikingclub.org/hikes-schedule**

Can we scrape it?
Context: This is a DC area hiking club with a hiking schedule that is published weeks or months in advance.

Are we scraping it?

**Comment by vabigdatamover** [comment]
Scraping the Capital Hiking Club URL does not provide a cost, this is located in a linked Meetup page.  

Hike Name:  **"_1idsK"**
<span class="_1idsK" data-hook="ev-list-item-title">Hike: Baltimore City Walk, MD</span>
Date & Time:  **"_5MWDj"**
<div class="_5MWDj" data-hook="date"><span class="">Mar 07, 8:00 AM – 6:30 PM</span></div>
Location: **"_297RP"**
<div class="_297RP" data-hook="location">Baltimore Inner Harbor, Inner Harbor, Baltimore, MD, USA</div>

**Comment by vabigdatamover** [comment]
The Capital Hiking Club schedule URL contains all the required text and could be scraped
`<script type="text/javascript">`

**Comment by vabigdatamover** [comment]
Capital Hiking Club Meetup page includes the location, date& time, and cost.  

Date & Time: 
`<div class="eventTimeDisplay text--labelSecondary text--small wrap--singleLine--truncate margin--halfBottom color-viridian"><time class="" datetime="1583543700000"><span class="eventTimeDisplay-startDate"><span>Fri, Mar 6</span>, <span class="eventTimeDisplay-startDate"><span>8:15 PM</span></span></span></time></div>`

[<span class="eventTimeDisplay-startDate"><span>8:15 PM</span></span>](url)

Location:
`<div class="text--ellipsisTwoLines text--sectionTitle margin--halfBottom"><a class="eventCardHead--title" href="/Capital-Hiking-Club/events/269091720/">Moonlight Hike: C&amp;O Canal Towpath, Great Falls, MD</a></div>`

Cost:
`<div class="flex-item text--secondary text--small"><div class="padding--left-half "><span>$26.00</span></div></div>`

[](https://www.meetup.com/Capital-Hiking-Club/events/)

**Comment by vabigdatamover** [comment]
Meetup require users subscribe to the Pro version in order to perform API calls, which cost $30-35 per month.  This page will require traditional scraping methods or access via calendar.

**Comment by csmcallister** [comment]
> Meetup require users subscribe to the Pro version in order to perform API calls, which cost $30-35 per month. This page will require traditional scraping methods or access via calendar.

Looks like you already got started to see if this event calendar is scrapable without recourse to the Meetup API @vabigdatamover. Do you want to finish that?

**Comment by vabigdatamover** [comment]
The Capital Hiking Club URL did not include any associated hiking cost, which were located on the Meetup page.  It was likely possible to scrape the websites with associated costs, however they have no hikes scheduled due to the Coronavirus, limiting the ability to scrape. This probably needs to be deferred until physical and social distancing ends.

**Comment by vabigdatamover** [comment]
All current and future hikes have been postponed until further notice

**Comment by csmcallister** [comment]
Issue cleaning...closing for now.
