### ISSUE TITLE
ENH: New Event Source: Northern Virginia Hiking Club

### ISSUE THREAD

**Issue by vabigdatamover** [DataKind-DC/capital-nature-ingest#229]
**Event Source Calendar**
https://www.meetup.com/NVHC-Hiking/events/
https://www.meetup.com/NVHC-Hiking/events/calendar/

General NVHC website, no calendar: https://www.nvhc.com/sched.html

**Can we scrape it?**
Context: This is a Northern Virginia based hiking club that has scheduled hikes posted weeks or months in advance. Membership is $5 per year, but hikes are free

**Are we scraping it?**

**Comment by vabigdatamover** [comment]
Here is documentation on utilizing Meetup API, this may be an easy or hard way to scrape events. But if someone figures it out, we can use this on numerous local outdoor events.

https://www.meetup.com/meetup_api/

https://www.datacamp.com/community/tutorials/meetup-api-data-json

**Comment by vabigdatamover** [comment]
Meetup require users subscribe to the Pro version in order to perform API calls, which cost $30-35 per month.  This page will require traditional scraping methods or access via calendar.

**Comment by csmcallister** [comment]
> Meetup require users subscribe to the Pro version in order to perform API calls, which cost $30-35 per month. This page will require traditional scraping methods or access via calendar.

Do you have a link to that calendar @vabigdatamover and would you be willing to see if it is scrapable?

**Comment by vabigdatamover** [comment]
Event Source Calendar
https://www.meetup.com/NVHC-Hiking/events/
https://www.meetup.com/NVHC-Hiking/events/calendar/
General NVHC website, no calendar: https://www.nvhc.com/sched.html

I can give them a try and work with Francisco if I run into any problems

**Comment by vabigdatamover** [comment]
All current and future hikes have been postponed until further notice

**Comment by csmcallister** [comment]
Issue cleaning...closing for now.
