### ISSUE TITLE
ENH: Virginia.org outdoor events

### ISSUE THREAD

**Issue by Frankie-Figz** [DataKind-DC/capital-nature-ingest#234]
**Virginia.org outdoor events**

## Can we scrape it?

https://www.virginia.org/directory/Events/stateparks/?city=STATEWIDE&categories=221

@akaahanui Would this be a valid event source provider to add to the scraping?

**Comment by Frankie-Figz** [comment]
Fernando Aguilar volunteered to take on this issue

**Comment by csmcallister** [comment]
Issue cleaning...closing for now.
