### ISSUE TITLE
ENH: Friends of James River

### ISSUE THREAD

**Issue by Frankie-Figz** [DataKind-DC/capital-nature-ingest#237]
## James River
 Some history on the James River: [link](https://dukeuniv.maps.arcgis.com/apps/Cascade/index.html?appid=db5f28a5d5524b00b63f25ffef67ab09)

## Can we scrape it?

https://www.jamesriverpark.org/calendar/

@akaahanui Is this a valid event source to add to the calender?

**Comment by csmcallister** [comment]
Issue cleaning...closing for now.
