### ISSUE TITLE
BUG: Use Fairfax County Park Authority's event calendar to scrape events

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#245]
**Expected Behavior**
The Fairfax Parks scraper should scrape their event calendar: https://www.fairfaxcounty.gov/parks/park-events-calendar

**Current Behavior**
Fraction of their events being pulled with existing scraper. Some parks with many programs like Ellanor C. Lawrence are not being pulled.

**Possible Solution**
Scrape the event calendar.

**Context**
This is an important event source for CN, so prioritize.

**Comment by csmcallister** [comment]
@akaahanui We're currently using https://www.fairfaxcounty.gov/parks/park-events-calendar to scrape events for this event source, but it appears their calendar now paginates their events, limiting users (and our scraper!) to the first 20 events. However, it appears I can use urls constructed like `https://www.fairfaxcounty.gov/parks/park-events-calendar?field_locationref_target_id=All&field_start_date_value=today&field_description_value=&field_end_date_value=&page=0` to iterate through the pages, so I think this can be a quick fix!

**Comment by akaahanui** [comment]
Fantastic news!

With Aloha,
Ana [image: ]

Capital Nature <http://www.capitalnature.org/>
Follow us on Facebook <https://www.facebook.com/capitalnaturedc/>
Submit an event
<https://docs.google.com/forms/d/e/1FAIpQLSfeTlhA7VbpGqVcIEeujEArEbF7LNyyQ0TkF5dmjA126TbCOQ/viewform>
for
our calendar!
