### ISSUE TITLE
BUG: Montgomery Parks events returning errors

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#248]
**Expected Behavior**
The Montgomery Parks scraper should scrape their event calendar: https://www.montgomeryparks.org/calendar/?v=0&cat=1746. Events have been pulled but with errors.

**Current Behavior**
Events being pulled but with errors:
1) Prices not populating. For those that are free, can a zero be populated in the price field?
2) Some event descriptions cut off or incomplete.

**Possible Solution**
Adjust coding for pricing and descriptions

**Context**
This is an important and abundant event source for CN, so prioritize.

**Comment by csmcallister** [comment]
@akaahanui Could you provide a link to one of the events where the description is cut off? I re-ran the scraper but cannot find an instance of this.

As for the event cost, I fixed that issue.

**Comment by akaahanui** [comment]
@csmcallister Hi Scott - Thanks for fixing the cost issue! After further review, I can't find a truncated description, so I must have confused them with another organizer. Sorry for the false alarm. Thanks!
