### ISSUE TITLE
BUG: US Botanic Gardens operational but with errors

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#250]
**Expected Behavior**
Please address operational errors for US Botanic Garden event calendar: https://www.usbg.gov/programs

**Current Behavior**
The USBG scraper is pulling events but with errors. We are not sure what the errors are.

**Comment by csmcallister** [comment]
@akaahanui The errors in this weren't really errors. I was logging instances where there was no event category. So this is fixed in b394999
