### ISSUE TITLE
BUG: Please fix broken Anacostia Riverkeeper scraper

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#253]
Expected Behavior
Please address broken scraper at event calendar: https://www.anacostiariverkeeper.org/events/

Current Behavior
The AR scraper is broken.

**Comment by csmcallister** [comment]
@akaahanui this one is broken since there aren't any events on their eventbrite page: https://www.eventbrite.com/o/anacostia-riverkeeper-10605256752

I fixed the code so that the code doesn't raise a false-positive error when there aren't any events.
