### ISSUE TITLE
BUG: Please fix the broken Building Bridges Across the River scraper

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#254]
**Expected Behavior**
Please address broken scraper at event calendar: https://bbardc.org/events/

**Current Behavior**
The Building Bridges Across the River scraper is broken.

**Comment by csmcallister** [comment]
@akaahanui for this one, most of the events on the site were missing the venue name, but it is obviously `11th Street Bridge Park`, so I've hardcoded that to prevent the errors.

**Comment by akaahanui** [comment]
Thanks @csmcallister !
