### ISSUE TITLE
NPS schema updates

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#30]
Some important event info was not captured, or needs modification, in the CSV file of scraped event data provided for the January 15th website launch.

## Current Behavior
The following changes are needed:

- [x] Event Category column says things like "Regular Event." This might be useful info, but we don't want it in this column. Probably best to rename this column something like "Event Frequency."
- [x] Time zone not captured.
- [x] Event Organizer column is empty. It would be best if we could say the specific park name here (rather than just NPS).
- [x] Event Cost Currency Symbol ($) not captured.

## Possible Solution
For park names, check the list of Event Organizers in the Wordpress admin page: http://capitalnature.org/wp-admin/edit.php?post_type=tribe_organizer. If the Organizer you're looking for is already listed, make sure it appears in the CSV file exactly as shown in Wordpress. If it's not listed yet, add it.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Just putting NPS as the organizer for all NPS events isn't specific enough, we want to be able to show the specific park name.

**Comment by csmcallister** [comment]
Two questions @bmvoss:
1. For the timezone, is the name sufficient (e.g. Eastern Standard Time)?
2. For the Event Category, the NPS API has a field called Category, which seems to always be "Regular Event" or Regular Program". I'm not sure if the word "Regular" is referring to the frequency of the event or not, so what do you think about me just dropping the Event Category column? We'd still have the Event Tags column, which does have some useful information.

**Comment by csmcallister** [comment]
@bmvoss I went ahead and made the suggested changes since it was pretty easy. CSV output is [here](https://docs.google.com/spreadsheets/d/1znSHrheEjqmb6OhhZ0ADse844A0Qp9RhsApczMGWSKk/edit#gid=1832608217). If that looks good, I'll merge #34

**Comment by bmvoss** [comment]
Hey @csmcallister , sorry I didn't reply sooner, these notifications were going to a different folder in my inbox that I'm just now sorting through. Here are my answers to your questions:

1. Time zones: I didn't see this before, but on the plugin info page (https://support.theeventscalendar.com/969953-CSV-file-examples-for-importing) it shows Eastern time as "America/New_York." So we could use that going forward.

2. Event Category: It's fine to keep the info in the "Regular Event"/"Regular Program" column, but it would be helpful if the column isn't called "Event Category" since that has a different meaning in the plugin. If it's possible, please rename this column to "Frequency" or "Program Type" or something like that.

3. I can't see the CSV output file, it looks like you linked to the Org Master Spreadsheet (https://docs.google.com/spreadsheets/d/1znSHrheEjqmb6OhhZ0ADse844A0Qp9RhsApczMGWSKk/edit#gid=0). Since you can't upload CSVs here, you could share it in the Capital Nature Google folder (https://drive.google.com/drive/folders/1Sf5wk1AGuwjiFw_BPXrkowGA4Df4lnuu).

4. Not sure why you can't access the Organizers and Venues pages. Does it work if you login at http://capitalnature.org/wp-admin/ first?

**Comment by csmcallister** [comment]
No worries @bmvoss 

1. I'll make that update soon.
2. Don't our column names have to match those in the [schema](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/event_schema.md)? I don't see `Frequency` or `Program Type` in there.
3. I'll add the csvs to the drive. I had been adding them as separate tabs on that Org Master Sheet.
4. It does not work even if I first login at http://capitalnature.org/wp-admin/  😭

**Comment by csmcallister** [comment]
@bmvoss Is this issue good to close for the NPS events? I still haven't been able to access the Organizers and Venues pages, but this data comes from an API, so I think we can be assured that the organizer and venue names are consistent.

**Comment by bmvoss** [comment]
@csmcallister Yes, this can be closed as long as the Organizers in the CSV output match the entries under 'park name' in the 'NPS sites' tab of the Google master spreadsheet.

**Comment by csmcallister** [comment]
cool beans. Given this requirement that new org and venue names need to be added to the admin site prior to a csv being uploaded, I’m gonna do some thinking on how that can be automated within the lamda process.
