### ISSUE TITLE
ANS schema updates

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#31]
Some important event info was not captured, or needs modification, in the CSV file of scraped event data provided for the January 15th website launch.

## Current Behavior
The following changes are needed:

- [x] Time zone not captured.
- [x] Event Organizer not captured.
- [x] Event Description not captured.
- [x] Event Cost not captured.
- [x] Event Cost Currency Symbol ($) not captured.

## Possible Solution
For Event Organizer, make sure the name (Audubon Naturalist Society) appears exactly as it does in the list of Event Organizers in the Wordpress admin page: http://capitalnature.org/wp-admin/edit.php?post_type=tribe_organizer. If the Organizer isn't ANS and isn't listed yet, add it.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by csmcallister** [comment]
closed by #48
