### ISSUE TITLE
Brookeside Gardens schema updates

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#32]
Some important event info was not captured, or needs modification, in the CSV file of scraped event data provided for the January 15th website launch.

## Current Behavior
The following changes are needed:
- [ ] Event Description not captured.
- [ ] Event Cost not captured.
- [ ] Event Cost Currency Symbol ($) not captured.

## Possible Solution
For Event Organizer, make sure the name appears exactly as it does in the list of Event Organizers in the Wordpress admin page: http://capitalnature.org/wp-admin/edit.php?post_type=tribe_organizer. If the Organizer isn't listed yet, add it.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by csmcallister** [comment]
closing since brookside gardens is handled in the montgomery module.
