### ISSUE TITLE
ENH: Add FONA (Friends of Natl Arboretum) schema updates

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#33]
Some important event info was not captured, or needs modification, in the CSV file of scraped event data provided for the January 15th website launch.

## Current Behavior
The following changes are needed:

- [x] Event Description not captured.
- [x] Event Cost not captured.
- [x] Event Cost Currency Symbol ($) not captured.

## Possible Solution
For Event Organizer, make sure the name appears *exactly* as it does in the list of Event Organizers in the Wordpress admin page: http://capitalnature.org/wp-admin/edit.php?post_type=tribe_organizer. If the Organizer isn't listed yet, add it.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by bmvoss** [comment]
@dominicwhite - I also realized that these events are actually US National Arboretum (USNA) events, not Friends of the National Arboretum (FONA) events. I'm not sure why they got associated with the FONA label, but since these sources have their own event listings, we should probably start calling these events USNA instead of FONA to avoid confusion.

USNA events (scraping): https://usna.usda.gov/visit/events-calendar/ (I assume this is the site you're scraping, although it appears to be down right now)

FONA events (manual for the time being): https://www.fona.org/events/soon/

**Comment by dominicwhite** [comment]
@bmvoss It should be Friends of the National Arboretum, not USNA. I got them from the Eventbrite page run by the Friends of the National Arboretum, as that source has an actual API: https://www.eventbrite.com/o/the-friends-of-the-national-arboretum-13276552841 . Some events appear in both Eventbrite & on the FONA website, whereas some events look like they only appear in one of the two.

**Comment by bmvoss** [comment]
@dominicwhite Ohhhhh, I didn't realize that. The Google spreadsheet shows FONA as manual and USNA as scraped. I'll fix that. Thanks!

**Comment by dominicwhite** [comment]
@bmvoss Unfortunately the USNA web calendar also wasn't working when we first stating working on the lambda scripts at Development Seed a few weeks ago - I don't know if this is a permanent outage or a temporary (shutdown-related?) issue.

**Comment by csmcallister** [comment]
Just saw this in the issue backlog. We're currently getting the event descriptions and currency symbol (hardcoded, of course). I can check to see if it's possible to get the cost as well.

**Comment by csmcallister** [comment]
Closed by e0d2fdc
