### ISSUE TITLE
CLN: Unrecognized Event Organizers in csv output

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#56]
## Expected Behavior
Values shown in the `Event Organizers` column of the csv output should correspond to the name of an organization we're tracking. Most of these orgs are listed in the [Github Event Sources](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/event_sources.md) table.

## Current Behavior
For a large number of events, the `Event Organizers` column in the csv output (file created 2/19/19) has names that don't appear to correspond to Organizations we're tracking (in most cases, the values shown are actually `Venues`). There are too many of these events to list here - [see this Google spreadsheet](https://docs.google.com/spreadsheets/d/1qmExJ8NfaMfUql9_mUAqxG3s4pMahy7LY0RPe8M0tqo/edit#gid=0).

## Possible Solution
I don't know.

## Context
This issue affects most/all of the sources that have been added since the 1/15 website launch.

**Comment by csmcallister** [comment]
Ahh I didn't realize that the `Event Organizers` field should always be the event source. I was sometimes using the event venue or another field that was scraped for cases where the event organizer wasn't necessarily the event source (a somewhat common occurrence for events located in county/state/national parks).

If you'd like, I can make the event organizer field always equal to the event source.

Then, for the event venues, I can devise a method for new events to see if their venue is one that we'e already scraped. If it isn't, I can add that venue to a master event venues spreadsheet. 

At the end of all this, you'll get three spreadsheets:
 - a events spreadsheet (like the 2/19/19 one)
 - a venue spreadsheet, which will contain a list of unique venue names (@ratherironic is supposed to share a template for that)
 - an organizer spreadsheet, which will contain a list of unique organizer names (@ratherironic is supposed to share a template for that)

Does that sound alright @bmvoss ?

**Comment by bmvoss** [comment]
@csmcallister -
Oh good, I'm glad this isn't too complicated! Yeah, the `Event Organizer` should just be the name of the source, the idea being that that way someone could search for, say, Casey Trees, and they should get all the events they're hosting. I've been adding new Organizers and Venues to the spreadsheet we uploaded before, so if you want to work off of those, I'll link them here (also in the Capital Nature Google Drive folder):

- [Organizers csv](https://drive.google.com/open?id=1oxVsU-OWRp-7X17PpKW5q-7QdNf4D78n) (just a list of names, must match `Organizers` in Events csv)

- [Venues csv](https://drive.google.com/open?id=13m_bVj8mJHsDeBj3442NfwVsnUNf6K5y) (name in first column must match the value under `Venue` in the Events csv)

(so I don't think you need other templates from @ratherironic )

**Comment by csmcallister** [comment]
@bmvoss are we good to close this issue now that the script outputs a csv for the organizers, venues, and events?

**Comment by bmvoss** [comment]
@csmcallister Yes, thanks! If it's possible to include some form of the word "scraped" in all the output filenames, that will help make sure we keep the scraped an manual outputs separate.
