### ISSUE TITLE
FIX: Fairfax Parks schema updates

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#69]
Event start and end times for this source don't appear in the Events csv output, although the Events do have start and end times shown on the event websites.

## Expected Behavior

- [ ] Events from `Organizer` **Fairfax Parks** don't have `start or end times`.

**Comment by csmcallister** [comment]
Looks like Fairfax County no longer displays the event times on the main calendar page, so I'll need to scrape each event's website to get the times. Seems doable upon first glance.

**Comment by bmvoss** [comment]
Interesting. I hope it's a fairly simple fix!

**Comment by csmcallister** [comment]
closed by #70
