### ISSUE TITLE
BUG: DUG Network event w/o start/end times

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#74]
## Expected Behavior
An event needs at least a start time. If it doesn't have one, then it should be dropped.

## Current Behavior
[This](http://dugnetwork.org/event/international-world-water-day-3/) event is in the output. Both the start and end times are empty.

## Possible Solution
Drop it with a conditional.

**Comment by csmcallister** [comment]
@pasrpr Would you want to tackle this?

**Comment by pasrpr** [comment]
Sure Scott, will take a look

**Comment by csmcallister** [comment]
closed by 0538b0c
