### ISSUE TITLE
BUG: Missing event website for some Arlington events

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#76]
## Expected Behavior
Each event has a website in its output. If you can't get one, then drop the event.

## Current Behavior
Three of the Arlington events (Crosshairs Garage Races) don't have a website, although a google search turns it up [here](https://www.crystalcity.org/do/crosshairs-garage-races).

**Comment by kirakrishnan** [comment]
@csmcallister can I work on this?

**Comment by csmcallister** [comment]
@kirakrishnan go for it!

**Comment by kirakrishnan** [comment]
@csmcallister created pull request

**Comment by csmcallister** [comment]
closed by 667a74e
