### ISSUE TITLE
ENH: Add location text to Event Descriptions

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#77]
- [x] For events that contain `Venue` information that can be interpreted as either Maryland, DC, or Virginia, add the two letter abbreviation for the state (MD/DC/VA), inside parentheses, and followed by a space, to the beginning of the `Event Description`. So Event Descriptions will start with one of the following (without the quotation marks):
- "(MD) "
- "(DC) "
- "(VA) "

## Context
This is a workaround solution to allow people to easily see where events are taking place. By putting the info at the beginning of the Event Description, it will always be visible when hovering over an event on the month calendar view, and will not require us to replace all the events that are already uploaded (because adding text to the event name will create a new event). This might not be possible for some events, because the Event Website doesn't clearly say which state it's in. But for those that do, this would be a useful feature.

**Comment by csmcallister** [comment]
@bmvoss I've got a solution that works for ~50% of the 842 events in the last scrape. Bumping that up much higher will require more time though, as I'd need to re-examine how each of the individual scrapers works and then create a bespoke solution. Even then, getting to 100% coverage is a long shot. With that said, do you think 50% coverage is good for now, or at least until we figure out if we're going to go with the event map option?

**Comment by bmvoss** [comment]
@csmcallister I think that's good for now. I tried to convey to Stella that this would be hard/impossible to do reliably, so 50% seems pretty decent. If getting much past that is a lot of work, IMO effort would be better spent on getting an actual map working. I will pass this on to Stella.
