### ISSUE TITLE
ENH: New event source: DC Parks & Rec

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#79]
The `Event Source` **DC Parks and Recreation** is a high priority for adding to the calendar. This source has not yet been evaluated for scrapability. Their events can be found here: http://dpr.events/

## Context
If this source is deemed not scrapable, please let me know ASAP.

**Comment by pasrpr** [comment]
Looks like http://dpr.events/ is not scrapable. Only when we click on RSVP and go to specific website, we are able to see the details.

**Comment by csmcallister** [comment]
Closing since this not scrapable.
